LIBIME_BIN_NAME = "libime_pinyindict"
LIBIME_REPOLOGY_URL = "https://repology.org/project/libime"
PARTIAL_DEPRECATED_APCONTINUE = "apcontinue"
PARTIAL_CONTINUE_DICT = "continue_dict"
PARTIAL_TITLES = "titles"
