# Copied from https://github.com/ArtalkJS/Artalk/blob/master/.github/workflows/release.yml
# MIT License
# Copyright (c) 2018-present, qwqcode and other contributors

name: Create release
run-name: Release ${{ inputs.semver }} ${{ inputs.dry_run && '(dry-run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: Which version you want to increment?
        options:
          - patch
          - minor
          - major
        required: true
      custom_version:
        description: Manual Custom Version (Special Purpose, v*)
        type: string
        required: false
      dry_run:
        description: 'Dry run?'
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/

      - name: Setup semver
        run: npm install -g semver

      - name: Handle Version Number
        run: |
          PREV_VERSION="$(cat mw2fcitx/version.py | grep 'PKG_VERSION' | awk '{print $3}' | sed 's/^"//; s/"$//')"

          if [ -n "${{ inputs.custom_version }}" ]; then
            NEXT_VERSION="${{ inputs.custom_version }}"
          else
            NEXT_VERSION="v$(semver --increment ${{ inputs.semver }} ${PREV_VERSION})"
          fi

          echo "PREV_VERSION=${PREV_VERSION}" >> $GITHUB_ENV
          echo "VERSION=${NEXT_VERSION}" >> $GITHUB_ENV

      - name: Print Next Version
        run: |
          echo "Version change: ${PREV_VERSION} -> ${VERSION}"

      - name: Modify version strings
        run: |
          # version.py
          sed -i 's/PKG_VERSION = "'$PREV_VERSION'"/PKG_VERSION = "'$VERSION'"/' mw2fcitx/version.py

          # pyproject.toml
          sed -i 's/version = "'$PREV_VERSION'"/version = "'$VERSION'"/' pyproject.toml

      - name: Print Git Diff
        run: git diff

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: ${{ !inputs.dry_run }}
        with:
          branch: 'rel/${{ env.VERSION }}'
          commit-message: 'chore: rel ${{ env.VERSION }}'
          title: 'Release ${{ env.VERSION }}'
          label: release
          body: |
            ## Release ${{ env.VERSION }}

            This PR is auto-generated, please check the changelog and confirm the release. 😀

            The build workflow will be triggered after the PR is merged.
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          assignees: ${{ github.actor }}
