# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
          cache: "poetry"

      - name: Run pylint
        run: |
          poetry install
          make lint

      - name: Test version mark
        run: make test_version

  buildtest:
    strategy:
      matrix:
        pyversion:
          - "3.9"
          - "3.10" # YAML trick: add "" especially between 3.10
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install libime
        run: sudo apt install -y libime-bin

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.pyversion }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.pyversion }}
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install
          poetry env info
          poetry show

      - name: Test with pytest
        env:
          TEST_REAL_WORLD: true
        run: make test

      - name: Run opencc-related tests
        env:
          TEST_REAL_WORLD: true
        run: |
          poetry install -E opencc
          make test_opencc

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_REPO_TOKEN }}
